#!/usr/bin/env node
/**
 * Write audit assessment results to skills.db
 * Generated by audit-skills skill — 2026-04-26
 *
 * Prerequisites: run `node scripts/init-skills-db.mjs` in BOTH repos first.
 */
import { DatabaseSync } from 'node:sqlite';
import { resolve } from 'node:path';
import { existsSync } from 'node:fs';

function openChecked(path) {
  if (!existsSync(path)) {
    console.error(`ERROR: ${path} does not exist. Run init-skills-db.mjs in that repo first.`);
    process.exit(1);
  }
  const db = new DatabaseSync(path);
  // Confirm schema is present before any work starts.
  const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='assessments'").all();
  if (tables.length === 0) {
    console.error(`ERROR: ${path} has no 'assessments' table. Run init-skills-db.mjs in that repo first.`);
    process.exit(1);
  }
  return db;
}

const workshopDb = openChecked(resolve('/workspace/projects/heathdev-workshop-plugin/skills.db'));
const cliDb = openChecked(resolve('/workspace/projects/sirmaelstroms-claude-code/skills.db'));

const now = new Date().toISOString();

const insert = (db) => db.prepare(`
  INSERT INTO assessments (
    skill_id, assessed_at,
    description_quality, output_quality, composability,
    agent_readiness, eval_coverage, usage_frequency,
    karpathy_eligible, notes, gaps, next_actions
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const workshopInsert = insert(workshopDb);
const cliInsert = insert(cliDb);

// heathdev-workshop-plugin assessments
const workshopData = [
  ['audit-skills', 4, 4, 4, 3, 0, 1, 1,
    'New skill, untested. Strong structure, good disambiguation after v1 refinement.',
    '["No eval suite","Never been run","No confidence reporting in output"]',
    '["Run first real audit to validate","Build eval suite","Add confidence bands to scores"]'],
  ['diagnose', 4, 5, 3, 4, 0, 4, 1,
    'Best-structured skill in the portfolio. Hypothesis matrix + edit gate are strong enforcement.',
    '["No eval suite","No upstream naming","Description lacks disambiguation from other skills"]',
    '["Add eval suite with real bug scenarios","Name upstream triggers in description"]'],
  ['eval-loop', 4, 4, 4, 3, 0, 1, 1,
    'New skill, untested. Well-specified loop mechanics and convergence criteria.',
    '["No eval suite","Never been run","Meta-skill testing is inherently harder"]',
    '["Run first loop on a real skill","Validate convergence detection works"]'],
  ['execute-wp', 3, 3, 5, 4, 0, 3, 1,
    'Pipeline crown jewel for composability. Progress log pattern is genuine innovation.',
    '["No eval suite","Output schema is progress entry not strict schema","Description lacks negative triggers"]',
    '["Add eval suite testing progress entry quality","Tighten output format"]'],
  ['grill-me', 3, 2, 3, 2, 0, 3, 0,
    'Intentionally minimal. Conversational nature makes it hard to evaluate structurally.',
    '["No output schema","Not agent-invocable","No karpathy eligibility — too interactive"]',
    '["Add lightweight output structure for resolved/deferred/risk items","Accept this is human-only"]'],
  ['improve-architecture', 3, 2, 4, 2, 0, 2, 0,
    'Good exploration pattern but relies heavily on human interaction at multiple gates.',
    '["No output schema","Not agent-invocable","Multiple required human decision points"]',
    '["Add structured output for candidate list","Consider whether steps 3+6 gates could have defaults"]'],
  ['parallel-explore', 4, 4, 3, 3, 0, 2, 1,
    'Strong forced-divergence pattern. Anti-convergence instruction is key innovation.',
    '["No eval suite","No explicit upstream/downstream naming","Cost check requires human"]',
    '["Add eval suite with diverse problem domains","Name pipeline connections","Consider auto-proceed for Sonnet runs"]'],
  ['spec', 3, 5, 5, 4, 0, 4, 1,
    'Most complex skill. 430 lines. Depth auto-selection + review level are sophisticated.',
    '["No eval suite","Description triggers are few for such a critical skill","3-depth complexity may confuse routing"]',
    '["Add eval suite testing depth selection accuracy","Add more trigger phrases to description"]'],
  ['spec-validate', 3, 3, 4, 4, 0, 3, 1,
    'Deterministic script-backed skill. Good pattern for testable evaluation.',
    '["No eval suite for the skill itself","Analysis layer output is prose not structured","Description lacks negative triggers"]',
    '["Add eval testing false-positive rate","Structure the analysis layer output"]'],
  ['ubiquitous-language', 3, 4, 3, 3, 0, 2, 1,
    'Good DDD integration. KB persistence + CLAUDE.md wiring are valuable.',
    '["No eval suite","Glossary quality hard to measure","Nobody reads the glossary downstream yet"]',
    '["Add eval testing glossary completeness","Wire spec-validate to check against glossary"]'],
];

// sirmaelstroms-claude-code assessments
const cliData = [
  ['cmd:general:code-cleanup', 4, 2, 2, 3, 0, 3, 1,
    'Good disambiguation from code-simplifier. Output is weak — no structured report.',
    '["No output schema","No composability — terminal","No eval suite"]',
    '["Add structured findings report","Define handoff to code-simplifier for auto-triggered follow-up"]'],
  ['cmd:general:code-explain', 4, 3, 1, 3, 0, 3, 1,
    'Multi-depth approach is smart. Completely terminal — output feeds nobody.',
    '["Terminal output","Some sections optional weakens schema","No eval suite"]',
    '["Make all 6 sections required","Add eval testing explanation depth matching"]'],
  ['cmd:general:docs-generate', 4, 3, 1, 3, 0, 2, 1,
    'Good language-specific format tables. Terminal, rarely used.',
    '["Terminal output","Variable output by doc type","No eval suite"]',
    '["Lower priority — rarely used","Add eval if usage increases"]'],
  ['cmd:general:lint', 4, 3, 2, 4, 0, 3, 1,
    'Strong auto-detection and severity categorization. Good defaults.',
    '["Weak composability — could feed code-cleanup","No eval suite"]',
    '["Define handoff to code-cleanup","Add eval testing linter detection accuracy"]'],
  ['cmd:general:sync-tasks', 3, 4, 2, 4, 0, 2, 1,
    'Most thorough command. 369 lines. Validation scripts, security checks, parsing rules.',
    '["Rarely used despite quality","Composability limited to TASKS.md ecosystem","No eval suite"]',
    '["Evaluate whether this fits current workflow","Add eval if kept active"]'],
  ['cmd:git:commit-push-pr', 4, 3, 2, 4, 0, 4, 1,
    'Highest frequency command. Safety protocol is good. Output varies per step.',
    '["No structured output contract","Composability is terminal (creates PR)","No eval suite"]',
    '["Add structured commit/PR metadata output","Add eval testing safety protocol adherence","Highest ROI target"]'],
  ['cmd:dotnet:add-package', 2, 2, 1, 3, 0, 2, 0,
    'Minimal description. Heavily interactive. .NET personal use declining.',
    '["Vague description","Terminal","Interactive-first design"]',
    '["Low priority — .NET leaving personal projects","Improve description if kept"]'],
  ['cmd:dotnet:build-test', 2, 3, 2, 4, 0, 3, 1,
    'Simple but well-structured. Fully autonomous. Used at work.',
    '["Vague description","Weak composability — could feed verify-app","No eval suite"]',
    '["Improve description","Define handoff to verify-app agent","Add eval for error parsing accuracy"]'],
  ['cmd:dotnet:new-project', 2, 2, 1, 3, 0, 1, 0,
    'Almost never used. Interactive scaffolding.',
    '["Vague description","Terminal","Rarely used"]',
    '["Lowest priority — consider archiving","Improve if needed"]'],
  ['agent:general:deep-research-agent', 2, 4, 2, 3, 0, 2, 1,
    'Good output structure with 7 sections. Description is vague for trigger routing.',
    '["Vague description","Terminal — reports not consumed by pipeline","No eval suite"]',
    '["Improve description with trigger examples","Add eval for report quality"]'],
  ['agent:general:security-engineer', 3, 3, 2, 3, 0, 2, 1,
    'Thorough checklists. OWASP integration. Rarely triggered.',
    '["No structured output template","Terminal","Low usage"]',
    '["Add structured finding template","Add eval testing OWASP coverage"]'],
  ['agent:general:tech-stack-researcher', 5, 4, 2, 3, 0, 2, 1,
    'Best description in the entire portfolio. 4 specific examples. Proactive trigger guidance.',
    '["Terminal — recommendations not consumed","Asks clarifying questions blocking autonomy"]',
    '["Add defaults for common constraint patterns","Wire recommendations into workshop pipeline"]'],
  ['agent:general:technical-writer', 2, 3, 2, 3, 0, 2, 1,
    'Good writing guidelines. Description is generic.',
    '["Vague description","Terminal","No output template"]',
    '["Improve description","Add structured output template","Lower priority"]'],
  ['agent:quality:code-simplifier', 3, 3, 3, 4, 0, 3, 1,
    'Good auto-trigger pattern. Before/after metrics are valuable signal.',
    '["No eval suite","Composability could be stronger with structured report"]',
    '["Add eval testing: line reduction, test preservation, no behavior change","Structure the output report"]'],
  ['agent:quality:verify-app', 2, 3, 3, 4, 0, 3, 1,
    'VERIFIED/BLOCKED verdicts are good binary signal. .NET-specific.',
    '["Vague description","Build/test focused on .NET only","No eval suite"]',
    '["Generalize beyond .NET","Add eval for verdict accuracy","Improve description"]'],
  ['agent:quality:adversarial-reviewer', 3, 3, 2, 3, 0, 2, 1,
    'Clear boundaries. Constructive alternative requirement is good.',
    '["Terminal output","No structured output template","Low usage"]',
    '["Add structured findings template with severity","Wire into spec review pipeline"]'],
  ['agent:dotnet:dotnet-architect', 2, 3, 2, 3, 0, 2, 0,
    'Comprehensive .NET patterns. Work context primarily.',
    '["Vague description","Terminal","Highly contextual — hard to eval"]',
    '["Low priority for personal improvement","Improve description if kept active"]'],
  ['agent:dotnet:dotnet-performance', 3, 3, 2, 3, 0, 2, 1,
    'Measurement-first mindset is strong. Profiling tool list is valuable reference.',
    '["Terminal output","No structured report template","Low usage personally"]',
    '["Add structured benchmark report template","Lower priority — work context"]'],
];

console.log('Writing heathdev-workshop assessments...');
for (const row of workshopData) {
  workshopInsert.run(row[0], now, ...row.slice(1));
}
console.log(`  ${workshopData.length} assessments written.`);

console.log('Writing sirmaelstroms-claude-code assessments...');
for (const row of cliData) {
  cliInsert.run(row[0], now, ...row.slice(1));
}
console.log(`  ${cliData.length} assessments written.`);

// Verify
const wCount = workshopDb.prepare('SELECT COUNT(*) as c FROM assessments').get();
const cCount = cliDb.prepare('SELECT COUNT(*) as c FROM assessments').get();
console.log(`\nTotal: ${wCount.c} workshop + ${cCount.c} CLI = ${wCount.c + cCount.c} assessments`);

workshopDb.close();
cliDb.close();
